import type { CatalogItem } from '../../../types.ts';
import { isPgDriver } from '../../db/driver.ts';
import { getEstimatorDb } from '../../db/connection.ts';
import { withPgTransaction, withSqliteTransaction, type DbExec } from '../../db/query.ts';

export const TAKEOFF_TOKEN_ALIAS_MAP: Record<string, string[]> = {
  gb: ['grab', 'bar', 'grab bar'],
  ch: ['coat', 'hook', 'coat hook'],
  snv: ['sanitary', 'napkin', 'vendor', 'sanitary napkin vendor'],
  snd: ['sanitary', 'napkin', 'disposal', 'sanitary napkin disposal'],
  ttd: ['toilet', 'tissue', 'dispenser', 'toilet tissue dispenser'],
  tpd: ['toilet', 'paper', 'dispenser'],
  ptd: ['paper', 'towel', 'dispenser', 'paper towel dispenser'],
  sd: ['soap', 'dispenser'],
  sc: ['shower', 'curtain'],
  scr: ['shower', 'curtain', 'rod', 'shower curtain rod'],
  sch: ['shower', 'curtain', 'hook', 'shower curtain hooks'],
  fss: ['folding', 'shower', 'seat', 'folding shower seat'],
  hd: ['hand', 'dryer'],
  nd: ['napkin', 'disposal'],
  rk: ['recess', 'kit'],
};

export const TAKEOFF_FAMILY_HINT_MAP: Record<string, string> = {
  gb: 'grab bar',
  ch: 'coat hook',
  snv: 'sanitary napkin vendor',
  snd: 'sanitary napkin disposal',
  ttd: 'toilet tissue dispenser',
  sd: 'soap dispenser',
  sc: 'shower curtain',
  scr: 'shower curtain rod',
  sch: 'shower curtain hooks',
  fss: 'folding shower seat',
  hd: 'hand dryer',
  b290: 'mirror',
  b212: 'coat hook',
  b270: 'sanitary napkin disposal',
  b2706: 'sanitary napkin vendor',
  w556509: 'toilet tissue dispenser',
  w51919: 'soap dispenser',
  b6806: 'grab bar',
  xlsb: 'hand dryer',
  tp: 'toilet partition',
  tpa: 'toilet partition',
  partition: 'toilet partition',
  partitions: 'toilet partition',
  compartment: 'toilet partition',
  compartments: 'toilet partition',
  us: 'urinal screen',
  us18: 'urinal screen',
  usb: 'urinal screen',
  pilaster: 'pilaster',
  pilasters: 'pilaster',
  hardware: 'partition hardware',
  hdpe: 'hdpe',
  phenolic: 'phenolic',
  stainless: 'stainless',
};

export const TAKEOFF_CATALOG_SEED_ITEMS: CatalogItem[] = [
  // ---- Toilet partitions (governed canonicals; no finish/mounting duplicate explosion) ----
  {
    id: 'takeoff-partition-scranton-eclipse-hdpe',
    sku: 'Scranton-Eclipse-HDPE',
    category: 'Toilet Partitions',
    family: 'toilet partition',
    recordGranularity: 'system_canonical',
    materialFamily: 'hdpe',
    systemSeries: 'Eclipse Partitions',
    privacyLevel: 'enhanced',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'compartment',
    estimatorNotes: 'Configurable system. Use project configuration + modifiers for height/system/mounting; avoid finish/color row variants.',
    description: 'Toilet Partition Compartment, HDPE (Eclipse)',
    manufacturer: 'Scranton Products',
    series: 'Eclipse Partitions',
    uom: 'EA',
    baseMaterialCost: 1850,
    baseLaborMinutes: 240,
    taxable: true,
    adaFlag: false,
    tags: ['partition', 'toilet partition', 'compartment', 'hdpe', 'scranton', 'eclipse'],
    installLaborFamily: 'toilet_partition_hdpe',
    notes: 'Manufacturer-backed series seed for HDPE partition coverage (compartment-level).',
    active: true,
  },
  {
    id: 'takeoff-partition-asi-phenolic-ultimate-privacy',
    sku: 'ASI-Phenolic-UltimatePrivacy',
    category: 'Toilet Partitions',
    family: 'toilet partition',
    recordGranularity: 'system_canonical',
    materialFamily: 'phenolic',
    systemSeries: 'Ultimate Privacy',
    privacyLevel: 'full_height',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'compartment',
    estimatorNotes: 'Configurable system. Treat “ultimate privacy” as series/privacy signal; do not model as separate color/finish SKUs.',
    description: 'Toilet Partition Compartment, Phenolic (Ultimate Privacy)',
    manufacturer: 'ASI Global Partitions',
    series: 'Ultimate Privacy',
    uom: 'EA',
    baseMaterialCost: 2150,
    baseLaborMinutes: 260,
    taxable: true,
    adaFlag: false,
    tags: ['partition', 'toilet partition', 'compartment', 'phenolic', 'asi', 'ultimate privacy'],
    installLaborFamily: 'toilet_partition_phenolic',
    notes: 'Manufacturer-backed series seed for phenolic partition coverage (compartment-level).',
    active: true,
  },
  {
    id: 'takeoff-partition-hadrian-steel-powder-coated',
    sku: 'Hadrian-PowderCoated-Steel',
    category: 'Toilet Partitions',
    family: 'toilet partition',
    recordGranularity: 'system_canonical',
    materialFamily: 'powder_coated_steel',
    systemSeries: 'Powder Coated Steel',
    privacyLevel: 'standard',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'compartment',
    estimatorNotes: 'Configurable system. Use modifiers for mounting/bracing/anchoring. Do not create finish-only duplicates.',
    description: 'Toilet Partition Compartment, Powder Coated Steel',
    manufacturer: 'Hadrian',
    series: 'Powder Coated Steel',
    uom: 'EA',
    baseMaterialCost: 1650,
    baseLaborMinutes: 230,
    taxable: true,
    adaFlag: false,
    tags: ['partition', 'toilet partition', 'compartment', 'steel', 'powder coated', 'hadrian'],
    installLaborFamily: 'toilet_partition_powder_coated_steel',
    notes: 'Manufacturer-backed series seed for powder coated steel partition coverage (compartment-level).',
    active: true,
  },
  {
    id: 'takeoff-partition-asi-hpl-plastic-laminate',
    sku: 'ASI-HPL-PlasticLaminate',
    category: 'Toilet Partitions',
    family: 'toilet partition',
    recordGranularity: 'system_canonical',
    materialFamily: 'hpl',
    systemSeries: 'Plastic Laminate',
    privacyLevel: 'standard',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'compartment',
    estimatorNotes: 'Configurable system. Plastic laminate (HPL) is a material family; do not represent colors/finishes as catalog rows.',
    description: 'Toilet Partition Compartment, Plastic Laminate (HPL)',
    manufacturer: 'ASI Global Partitions',
    series: 'Plastic Laminate',
    uom: 'EA',
    baseMaterialCost: 1750,
    baseLaborMinutes: 240,
    taxable: true,
    adaFlag: false,
    tags: ['partition', 'toilet partition', 'compartment', 'plastic laminate', 'hpl', 'asi'],
    installLaborFamily: 'toilet_partition_hpl',
    notes: 'Manufacturer-backed category seed for plastic laminate partition coverage (compartment-level).',
    active: true,
  },
  {
    id: 'takeoff-partition-hadrian-stainless-steel',
    sku: 'Hadrian-Stainless',
    category: 'Toilet Partitions',
    family: 'toilet partition',
    recordGranularity: 'system_canonical',
    materialFamily: 'stainless',
    systemSeries: 'Stainless Steel',
    privacyLevel: 'standard',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'compartment',
    estimatorNotes: 'Configurable system. Stainless is a material family; avoid duplicating rows for minor phrasing.',
    description: 'Toilet Partition Compartment, Stainless Steel',
    manufacturer: 'Hadrian',
    series: 'Stainless Steel',
    uom: 'EA',
    baseMaterialCost: 2650,
    baseLaborMinutes: 280,
    taxable: true,
    adaFlag: false,
    tags: ['partition', 'toilet partition', 'compartment', 'stainless', 'hadrian'],
    installLaborFamily: 'toilet_partition_stainless',
    notes: 'Manufacturer-backed series seed for stainless steel partition coverage (compartment-level).',
    active: true,
  },
  {
    id: 'takeoff-urinal-screen-scranton-hdpe',
    sku: 'Scranton-UrinalScreen-HDPE',
    category: 'Toilet Partitions',
    family: 'urinal screen',
    recordGranularity: 'system_canonical',
    materialFamily: 'hdpe',
    systemSeries: null,
    privacyLevel: 'standard',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Configurable system. Avoid duplicating rows for minor mounting phrasing; use modifiers if needed.',
    description: 'Urinal Screen, HDPE',
    manufacturer: 'Scranton Products',
    uom: 'EA',
    baseMaterialCost: 420,
    baseLaborMinutes: 70,
    taxable: true,
    adaFlag: false,
    tags: ['urinal screen', 'privacy screen', 'hdpe', 'scranton'],
    installLaborFamily: 'urinal_screen_hdpe',
    notes: 'Manufacturer-backed seed for urinal screen coverage.',
    active: true,
  },
  {
    id: 'takeoff-urinal-screen-hadrian-steel',
    sku: 'Hadrian-UrinalScreen-Steel',
    category: 'Toilet Partitions',
    family: 'urinal screen',
    recordGranularity: 'system_canonical',
    materialFamily: 'powder_coated_steel',
    systemSeries: null,
    privacyLevel: 'standard',
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Configurable system. Use mounting/bracing/anchoring modifiers; do not create finish-only catalog rows.',
    description: 'Urinal Screen, Powder Coated Steel',
    manufacturer: 'Hadrian',
    uom: 'EA',
    baseMaterialCost: 360,
    baseLaborMinutes: 65,
    taxable: true,
    adaFlag: false,
    tags: ['urinal screen', 'privacy screen', 'steel', 'powder coated', 'hadrian'],
    installLaborFamily: 'urinal_screen_steel',
    notes: 'Manufacturer-backed seed for urinal screen coverage.',
    active: true,
  },

  // ---- Fire protection specialties (governed canonicals; mounting + rating as attributes, not SKU explosion) ----
  {
    id: 'takeoff-fire-fe-cabinet-canonical',
    sku: 'FE-CABINET',
    category: 'Fire Protection Specialties',
    family: 'fire extinguisher cabinet',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: null,
    privacyLevel: null,
    manufacturerConfiguredItem: false,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use mounting and fire-rated selection as attributes (surface/semi-recessed/recessed; fire-rated) instead of separate SKUs.',
    description: 'Fire Extinguisher Cabinet',
    manufacturer: 'Larsen',
    model: '2409',
    uom: 'EA',
    baseMaterialCost: 145,
    baseLaborMinutes: 40,
    taxable: true,
    adaFlag: false,
    tags: ['fire extinguisher cabinet', 'fe cabinet', 'larsen', '2409'],
    installLaborFamily: 'fire_extinguisher_cabinet',
    notes: 'Manufacturer-backed seed for FE cabinet baseline; variants handled via attributes.',
    active: true,
  },
  {
    id: 'takeoff-fire-aed-cabinet-canonical',
    sku: 'AED-CABINET',
    category: 'Fire Protection Specialties',
    family: 'aed cabinet',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: null,
    privacyLevel: null,
    manufacturerConfiguredItem: false,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use mounting selection as an attribute (surface/recessed); avoid SKU variants for minor phrasing.',
    description: 'AED Cabinet',
    manufacturer: 'Larsen',
    model: '2400',
    uom: 'EA',
    baseMaterialCost: 175,
    baseLaborMinutes: 35,
    taxable: true,
    adaFlag: false,
    tags: ['aed cabinet', 'aed', 'larsen'],
    installLaborFamily: 'aed_cabinet',
    notes: 'Manufacturer-backed seed for AED cabinet baseline; variants handled via attributes.',
    active: true,
  },

  // ---- Lockers (governed canonicals; tier/system variety without KD/welded row explosion) ----
  {
    id: 'takeoff-locker-steel-single-tier',
    sku: 'LOCKER-STEEL-1T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: 'Standard steel',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use assembly attribute for KD vs welded/fully assembled. Use tier canonicals (1T/2T/3T/6T) for base cost differences.',
    description: 'Locker, Steel, Single Tier (1T)',
    manufacturer: 'Penco',
    model: 'Vanguard™',
    series: 'Vanguard™ Metal Storage Lockers',
    uom: 'EA',
    baseMaterialCost: 185,
    baseLaborMinutes: 45,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'single tier', '1 tier', 'steel', 'penco'],
    installLaborFamily: 'locker',
    notes: 'Governed canonical for single-tier steel lockers.',
    active: true,
  },
  {
    id: 'takeoff-locker-steel-double-tier',
    sku: 'LOCKER-STEEL-2T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: 'Standard steel',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use assembly attribute for KD vs welded/fully assembled.',
    description: 'Locker, Steel, Double Tier (2T)',
    manufacturer: 'Penco',
    model: 'Vanguard™',
    series: 'Vanguard™ Metal Storage Lockers',
    uom: 'EA',
    baseMaterialCost: 210,
    baseLaborMinutes: 60,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'double tier', '2 tier', 'steel', 'penco'],
    installLaborFamily: 'locker',
    notes: 'Governed canonical for double-tier steel lockers.',
    active: true,
  },
  {
    id: 'takeoff-locker-steel-triple-tier',
    sku: 'LOCKER-STEEL-3T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: 'Standard steel',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use assembly attribute for KD vs welded/fully assembled.',
    description: 'Locker, Steel, Triple Tier (3T)',
    manufacturer: 'Penco',
    model: 'Vanguard™',
    series: 'Vanguard™ Metal Storage Lockers',
    uom: 'EA',
    baseMaterialCost: 235,
    baseLaborMinutes: 70,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'triple tier', '3 tier', 'steel', 'penco'],
    installLaborFamily: 'locker',
    notes: 'Governed canonical for triple-tier steel lockers.',
    active: true,
  },
  {
    id: 'takeoff-locker-steel-six-tier',
    sku: 'LOCKER-STEEL-6T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'steel',
    systemSeries: 'Standard steel',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use assembly attribute for KD vs welded/fully assembled. Six-tier/box lockers are materially different from 1T/2T/3T.',
    description: 'Locker, Steel, Six Tier / Box (6T)',
    manufacturer: 'Penco',
    model: 'Vanguard™',
    series: 'Vanguard™ Metal Storage Lockers',
    uom: 'EA',
    baseMaterialCost: 260,
    baseLaborMinutes: 80,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'six tier', '6 tier', 'box locker', 'steel', 'penco'],
    installLaborFamily: 'locker',
    notes: 'Governed canonical for six-tier (box) steel lockers.',
    active: true,
  },
  {
    id: 'takeoff-locker-bench-48',
    sku: 'LOCKER-BENCH-48',
    category: 'Lockers',
    family: 'bench',
    recordGranularity: 'component',
    materialFamily: 'wood',
    systemSeries: 'Locker bench',
    privacyLevel: null,
    manufacturerConfiguredItem: false,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: false,
    defaultUnit: 'ea',
    estimatorNotes: 'Bench is often separate scope; keep as its own canonical line.',
    description: 'Locker Bench, 48"',
    manufacturer: 'Penco',
    series: 'Standard',
    uom: 'EA',
    baseMaterialCost: 125,
    baseLaborMinutes: 30,
    taxable: true,
    adaFlag: false,
    tags: ['bench', 'locker bench', '48'],
    installLaborFamily: 'bench',
    notes: 'Governed canonical for a basic locker-room bench.',
    active: true,
  },

  {
    id: 'takeoff-locker-asi-traditional-steel',
    sku: 'ASI-LOCKER-TRADITIONAL-STEEL',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'system_canonical',
    materialFamily: 'steel',
    systemSeries: 'Traditional Collection',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Series-level canonical for ASI Storage Solutions steel lockers. Use tier-specific canonicals when the tier is explicit; otherwise this is a safe baseline for “steel lockers” scope.',
    description: 'Locker System, Steel (Traditional Collection)',
    manufacturer: 'ASI Storage Solutions',
    series: 'Traditional Collection',
    uom: 'EA',
    baseMaterialCost: 220,
    baseLaborMinutes: 60,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'steel locker', 'asi', 'traditional collection'],
    installLaborFamily: 'locker',
    notes: 'Manufacturer-backed series seed for locker coverage (steel system baseline).',
    active: true,
  },

  {
    id: 'takeoff-locker-scranton-tufftec-hdpe-1t',
    sku: 'Scranton-Tufftec-HDPE-1T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'hdpe',
    systemSeries: 'Tufftec®',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'HDPE solid plastic lockers. Avoid finish variants; use assembly attribute for shipped KD vs factory-assembled when stated.',
    description: 'Locker, HDPE Solid Plastic, Single Tier (Tufftec®)',
    manufacturer: 'Scranton Products',
    series: 'Tufftec® Lockers',
    uom: 'EA',
    baseMaterialCost: 340,
    baseLaborMinutes: 75,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'plastic locker', 'hdpe', 'scranton', 'tufftec', 'single tier'],
    installLaborFamily: 'locker',
    notes: 'Manufacturer-backed series seed for HDPE plastic locker coverage (single tier).',
    active: true,
  },

  {
    id: 'takeoff-locker-scranton-tufftec-hdpe-6t',
    sku: 'Scranton-Tufftec-HDPE-6T',
    category: 'Lockers',
    family: 'locker',
    recordGranularity: 'component',
    materialFamily: 'hdpe',
    systemSeries: 'Tufftec®',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'HDPE solid plastic lockers. Six-tier/box style is a materially different base than 1T/2T/3T.',
    description: 'Locker, HDPE Solid Plastic, Six Tier / Box (Tufftec®)',
    manufacturer: 'Scranton Products',
    series: 'Tufftec® Lockers',
    uom: 'EA',
    baseMaterialCost: 420,
    baseLaborMinutes: 95,
    taxable: true,
    adaFlag: false,
    tags: ['locker', 'plastic locker', 'hdpe', 'scranton', 'tufftec', 'six tier', 'box locker'],
    installLaborFamily: 'locker',
    notes: 'Manufacturer-backed series seed for HDPE plastic locker coverage (six tier/box).',
    active: true,
  },

  // ---- Visual display boards (governed canonicals; avoid size/trim/finish row explosion) ----
  {
    id: 'takeoff-vdb-markerboard-canonical',
    sku: 'VDB-MARKERBOARD',
    category: 'Visual Display Boards',
    family: 'markerboard',
    recordGranularity: 'system_canonical',
    materialFamily: 'porcelain',
    systemSeries: 'Series board',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use as basis-of-design markerboard. Do not create separate rows for every size/frame/finish; handle trim/surface as governed attributes where needed.',
    description: 'Markerboard System (Wall-Mounted)',
    manufacturer: 'Claridge',
    model: 'Series Boards',
    uom: 'EA',
    baseMaterialCost: 320,
    baseLaborMinutes: 60,
    taxable: true,
    adaFlag: false,
    tags: ['markerboard', 'whiteboard', 'writing board', 'claridge'],
    installLaborFamily: 'visual_display_board',
    notes: 'Governed canonical for markerboards; size and trim handled by project configuration/attributes.',
    active: true,
  },
  {
    id: 'takeoff-vdb-tackboard-canonical',
    sku: 'VDB-TACKBOARD',
    category: 'Visual Display Boards',
    family: 'tackboard',
    recordGranularity: 'system_canonical',
    materialFamily: 'cork',
    systemSeries: 'Series board',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Use as basis-of-design tackboard/bulletin board. Avoid size/frame duplicates; treat surface/trim as governed options.',
    description: 'Tackboard / Bulletin Board System (Wall-Mounted)',
    manufacturer: 'Claridge',
    model: 'Series Boards',
    uom: 'EA',
    baseMaterialCost: 240,
    baseLaborMinutes: 45,
    taxable: true,
    adaFlag: false,
    tags: ['tackboard', 'bulletin board', 'cork board', 'claridge'],
    installLaborFamily: 'visual_display_board',
    notes: 'Governed canonical for tackboards; size and trim handled by project configuration/attributes.',
    active: true,
  },
  {
    id: 'takeoff-vdb-asi-porcelain-9800',
    sku: 'ASI-VDB-9800-PORC',
    category: 'Visual Display Boards',
    family: 'markerboard',
    recordGranularity: 'system_canonical',
    materialFamily: 'porcelain',
    systemSeries: 'Series 9800',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'ASI Visual Display Products basis-of-design porcelain writing surface; series is a trim system. Avoid duplicating rows for each size.',
    description: 'Markerboard System, Porcelain (Series 9800 Trim)',
    manufacturer: 'ASI Visual Display Products',
    series: 'Series 9800',
    uom: 'EA',
    baseMaterialCost: 340,
    baseLaborMinutes: 65,
    taxable: true,
    adaFlag: false,
    tags: ['markerboard', 'whiteboard', 'porcelain', 'asi', 'series 9800'],
    installLaborFamily: 'visual_display_board',
    notes: 'Manufacturer-backed series seed for porcelain markerboard coverage.',
    active: true,
  },
  {
    id: 'takeoff-vdb-asi-cork-9800',
    sku: 'ASI-VDB-9800-CORK',
    category: 'Visual Display Boards',
    family: 'tackboard',
    recordGranularity: 'system_canonical',
    materialFamily: 'cork',
    systemSeries: 'Series 9800',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'ASI Visual Display Products cork tackboard; series is a trim system. Avoid duplicating rows for each size.',
    description: 'Tackboard System, Cork (Series 9800 Trim)',
    manufacturer: 'ASI Visual Display Products',
    series: 'Series 9800',
    uom: 'EA',
    baseMaterialCost: 260,
    baseLaborMinutes: 55,
    taxable: true,
    adaFlag: false,
    tags: ['tackboard', 'bulletin board', 'cork', 'asi', 'series 9800'],
    installLaborFamily: 'visual_display_board',
    notes: 'Manufacturer-backed series seed for cork tackboard coverage.',
    active: true,
  },

  // ---- Wall / corner protection (governed canonicals; mounting as attributes, no dimension/finish row explosion) ----
  {
    id: 'takeoff-wcp-corner-guard',
    sku: 'WCP-CORNER-GUARD',
    category: 'Wall / Corner Protection',
    family: 'corner guard',
    recordGranularity: 'system_canonical',
    materialFamily: 'acrovyn',
    systemSeries: 'Acrovyn®',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'lf',
    estimatorNotes: 'Basis-of-design corner guard. Use mounting attribute for adhesive vs mechanical fastening; do not create rows per size/finish.',
    description: 'Corner Guard System (Acrovyn®/PVC)',
    manufacturer: 'Construction Specialties',
    series: 'Acrovyn® Wall Protection',
    uom: 'LF',
    baseMaterialCost: 9,
    baseLaborMinutes: 8,
    taxable: true,
    adaFlag: false,
    tags: ['corner guard', 'wall protection', 'acrovyn', 'c/s', 'construction specialties'],
    installLaborFamily: 'wall_protection',
    notes: 'Governed canonical for corner guards (per LF).',
    active: true,
  },
  {
    id: 'takeoff-wcp-chair-rail',
    sku: 'WCP-CHAIR-RAIL',
    category: 'Wall / Corner Protection',
    family: 'chair rail',
    recordGranularity: 'system_canonical',
    materialFamily: 'acrovyn',
    systemSeries: 'Acrovyn®',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'lf',
    estimatorNotes: 'Basis-of-design chair rail / wall guard. Use mounting attribute (adhesive vs mechanical) and avoid size/finish duplicates.',
    description: 'Chair Rail / Wall Guard System (Acrovyn®)',
    manufacturer: 'Construction Specialties',
    series: 'Acrovyn® Wall Protection',
    uom: 'LF',
    baseMaterialCost: 14,
    baseLaborMinutes: 10,
    taxable: true,
    adaFlag: false,
    tags: ['chair rail', 'wall guard', 'wall protection', 'acrovyn', 'c/s', 'construction specialties'],
    installLaborFamily: 'wall_protection',
    notes: 'Governed canonical for chair rails/wall guards (per LF).',
    active: true,
  },
  {
    id: 'takeoff-wcp-crash-rail',
    sku: 'WCP-CRASH-RAIL',
    category: 'Wall / Corner Protection',
    family: 'crash rail',
    recordGranularity: 'system_canonical',
    materialFamily: 'acrovyn',
    systemSeries: 'Acrovyn®',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'lf',
    estimatorNotes: 'Basis-of-design crash rail. Mounting variants should be attributes, not separate SKUs.',
    description: 'Crash Rail System (Acrovyn®)',
    manufacturer: 'Construction Specialties',
    series: 'Acrovyn® Crash Rails',
    model: 'SCR',
    uom: 'LF',
    baseMaterialCost: 22,
    baseLaborMinutes: 12,
    taxable: true,
    adaFlag: false,
    tags: ['crash rail', 'wall protection', 'acrovyn', 'scr', 'c/s', 'construction specialties'],
    installLaborFamily: 'wall_protection',
    notes: 'Governed canonical for crash rails (per LF).',
    active: true,
  },

  // ---- Postal specialties (governed canonicals; configuration handled via metadata/attributes, not SKU explosion) ----
  {
    id: 'takeoff-postal-4c-horizontal',
    sku: 'POSTAL-4C-HORIZONTAL',
    category: 'Postal Specialties',
    family: 'mailbox',
    recordGranularity: 'system_canonical',
    materialFamily: 'steel',
    systemSeries: 'STD-4C',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'USPS STD-4C horizontal mailboxes. Do not create rows for every door count / mount type; treat configuration as project setup.',
    description: '4C Horizontal Mailbox System (USPS STD-4C)',
    manufacturer: 'Florence Corporation',
    series: 'Versatile™ STD-4C',
    model: '4C',
    uom: 'EA',
    baseMaterialCost: 2850,
    baseLaborMinutes: 210,
    taxable: true,
    adaFlag: false,
    tags: ['4c', 'std-4c', 'horizontal mailbox', 'mailbox', 'postal', 'florence'],
    installLaborFamily: 'postal_specialty',
    notes: 'Manufacturer-backed canonical anchor for 4C horizontal mailbox scope.',
    active: true,
  },
  {
    id: 'takeoff-postal-4c-horizontal-salsbury-3500',
    sku: 'POSTAL-4C-HORIZONTAL-3500',
    category: 'Postal Specialties',
    family: 'mailbox',
    recordGranularity: 'system_canonical',
    materialFamily: 'steel',
    systemSeries: '3500',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes:
      'Salsbury 4C horizontal mailboxes. Do not create rows for every door count / trim; treat configuration as project setup.',
    description: '4C Horizontal Mailbox System (Salsbury 3500 Series)',
    manufacturer: 'Salsbury Industries',
    series: '3500 Series',
    model: '3500',
    uom: 'EA',
    baseMaterialCost: 2650,
    baseLaborMinutes: 210,
    taxable: true,
    adaFlag: false,
    tags: ['4c', 'horizontal mailbox', 'mailbox', 'postal', 'salsbury', '3500'],
    installLaborFamily: 'postal_specialty',
    notes: 'Alternate manufacturer-backed canonical anchor for 4C horizontal mailbox scope.',
    active: true,
  },
  {
    id: 'takeoff-postal-cbu-1570',
    sku: 'POSTAL-CBU-1570',
    category: 'Postal Specialties',
    family: 'cluster box unit',
    recordGranularity: 'system_canonical',
    materialFamily: 'aluminum',
    systemSeries: '1570',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Cluster Box Unit (CBU). Avoid per-door SKUs; model door count/type as configuration.',
    description: 'Cluster Box Unit (CBU) System',
    manufacturer: 'Florence Corporation',
    series: '1570 Series',
    model: '1570',
    uom: 'EA',
    baseMaterialCost: 2600,
    baseLaborMinutes: 240,
    taxable: true,
    adaFlag: false,
    tags: ['cbu', 'cluster box unit', 'cluster mailbox', 'postal', 'florence', '1570'],
    installLaborFamily: 'postal_specialty',
    notes: 'Manufacturer-backed canonical anchor for cluster box units.',
    active: true,
  },
  {
    id: 'takeoff-postal-parcel-locker-1590',
    sku: 'POSTAL-PARCEL-LOCKER-1590',
    category: 'Postal Specialties',
    family: 'parcel locker',
    recordGranularity: 'system_canonical',
    materialFamily: 'aluminum',
    systemSeries: '1590',
    privacyLevel: null,
    manufacturerConfiguredItem: true,
    canonicalMatchAnchor: true,
    exactComponentSku: false,
    requiresProjectConfiguration: true,
    defaultUnit: 'ea',
    estimatorNotes: 'Outdoor parcel lockers. Avoid per-compartment SKUs; model compartment count/type as configuration.',
    description: 'Outdoor Parcel Locker System',
    manufacturer: 'Florence Corporation',
    series: '1590 Series',
    model: '1590',
    uom: 'EA',
    baseMaterialCost: 2250,
    baseLaborMinutes: 210,
    taxable: true,
    adaFlag: false,
    tags: ['parcel locker', 'package locker', 'postal', 'florence', '1590'],
    installLaborFamily: 'postal_specialty',
    notes: 'Manufacturer-backed canonical anchor for outdoor parcel lockers.',
    active: true,
  },

  {
    id: 'takeoff-gb-36',
    sku: 'B-6806-36',
    category: 'Toilet Accessories',
    family: 'grab bar',
    description: 'Grab Bar - 36" SS',
    manufacturer: 'Bobrick',
    model: 'B-6806',
    uom: 'EA',
    baseMaterialCost: 52,
    baseLaborMinutes: 20,
    taxable: true,
    adaFlag: true,
    tags: ['gb', 'grab bar', '36'],
    notes: 'Takeoff registry seed for matrix shorthand coverage.',
    active: true,
  },
  {
    id: 'takeoff-gb-b6806-42',
    sku: 'B-6806-42',
    category: 'Toilet Accessories',
    family: 'grab bar',
    description: 'Grab Bar - 42" SS',
    manufacturer: 'Bobrick',
    model: 'B-6806',
    uom: 'EA',
    baseMaterialCost: 58,
    baseLaborMinutes: 22,
    taxable: true,
    adaFlag: true,
    tags: ['gb', 'grab bar', '42', 'b6806'],
    notes: 'Takeoff registry seed for model-based grab bar shorthand.',
    active: true,
  },
  {
    id: 'takeoff-gb-2wall',
    sku: '2-WALL-GB',
    category: 'Toilet Accessories',
    family: 'grab bar',
    description: 'Two-Wall Grab Bar Assembly',
    manufacturer: 'Bobrick',
    model: 'B-2WALL',
    uom: 'EA',
    baseMaterialCost: 90,
    baseLaborMinutes: 35,
    taxable: true,
    adaFlag: true,
    tags: ['2 wall gb', 'two wall grab bar', 'grab bar'],
    notes: 'Takeoff registry seed for two-wall grab bar shorthand.',
    active: true,
  },
  {
    id: 'takeoff-ch-b212',
    sku: 'CH-B212',
    category: 'Toilet Accessories',
    family: 'coat hook',
    description: 'Coat Hook',
    manufacturer: 'Bobrick',
    model: 'B212',
    uom: 'EA',
    baseMaterialCost: 18,
    baseLaborMinutes: 10,
    taxable: true,
    adaFlag: false,
    tags: ['ch', 'coat hook', 'b212'],
    notes: 'Takeoff registry seed for Bobrick coat hook shorthand.',
    active: true,
  },
  {
    id: 'takeoff-ch-asi-0711',
    sku: 'ASI-0711',
    category: 'Toilet Accessories',
    family: 'coat hook',
    description: 'Coat Hook, Surface Mount',
    manufacturer: 'ASI',
    model: '0711',
    uom: 'EA',
    baseMaterialCost: 16,
    baseLaborMinutes: 10,
    taxable: true,
    adaFlag: false,
    tags: ['coat hook', 'asi', '0711'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (coat hook).',
    active: true,
  },
  {
    id: 'takeoff-snv-b2706',
    sku: 'B-2706',
    category: 'Toilet Accessories',
    family: 'sanitary napkin vendor',
    description: 'Sanitary Napkin Vendor',
    manufacturer: 'Bobrick',
    model: 'B-2706',
    uom: 'EA',
    baseMaterialCost: 120,
    baseLaborMinutes: 25,
    taxable: true,
    adaFlag: false,
    tags: ['snv', 'sanitary napkin vendor', 'b2706'],
    notes: 'Takeoff registry seed for sanitary napkin vendor shorthand.',
    active: true,
  },
  {
    id: 'takeoff-snd-b270',
    sku: 'B-270',
    category: 'Toilet Accessories',
    family: 'sanitary napkin disposal',
    description: 'Sanitary Napkin Disposal',
    manufacturer: 'Bobrick',
    model: 'B-270',
    uom: 'EA',
    baseMaterialCost: 54,
    baseLaborMinutes: 16,
    taxable: true,
    adaFlag: false,
    tags: ['snd', 'sanitary napkin disposal', 'b270'],
    notes: 'Takeoff registry seed for sanitary napkin disposal shorthand.',
    active: true,
  },
  {
    id: 'takeoff-ttd-w556509',
    sku: 'ASI-W556509',
    category: 'Toilet Accessories',
    family: 'toilet tissue dispenser',
    description: 'Toilet Tissue Dispenser',
    manufacturer: 'ASI',
    model: 'W556509',
    uom: 'EA',
    baseMaterialCost: 68,
    baseLaborMinutes: 18,
    taxable: true,
    adaFlag: false,
    tags: ['ttd', 'toilet tissue dispenser', 'w556509'],
    notes: 'Takeoff registry seed for ASI tissue dispenser shorthand.',
    active: true,
  },
  {
    id: 'takeoff-ttd-asi-0030',
    sku: 'ASI-0030',
    category: 'Toilet Accessories',
    family: 'toilet tissue dispenser',
    description: 'Toilet Tissue Dispenser, Surface Mount (Dual Roll)',
    manufacturer: 'ASI',
    model: '0030',
    uom: 'EA',
    baseMaterialCost: 72,
    baseLaborMinutes: 18,
    taxable: true,
    adaFlag: false,
    tags: ['ttd', 'toilet tissue dispenser', 'asi', '0030', 'dual roll'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (tissue dispenser).',
    active: true,
  },
  {
    id: 'takeoff-ttd-bobrick-b2888',
    sku: 'B-2888',
    category: 'Toilet Accessories',
    family: 'toilet tissue dispenser',
    description: 'Toilet Tissue Dispenser, Surface Mount',
    manufacturer: 'Bobrick',
    model: 'B-2888',
    uom: 'EA',
    baseMaterialCost: 78,
    baseLaborMinutes: 18,
    taxable: true,
    adaFlag: false,
    tags: ['ttd', 'toilet tissue dispenser', 'bobrick', 'b-2888'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (tissue dispenser).',
    active: true,
  },
  {
    id: 'takeoff-sd-w51919-04',
    sku: 'ASI-W51919-04',
    category: 'Toilet Accessories',
    family: 'soap dispenser',
    description: 'Soap Dispenser with LTX-12 Top Fill',
    manufacturer: 'ASI',
    model: 'W51919-04',
    uom: 'EA',
    baseMaterialCost: 88,
    baseLaborMinutes: 20,
    taxable: true,
    adaFlag: false,
    tags: ['sd', 'soap dispenser', 'w51919-04', 'ltx-12'],
    notes: 'Takeoff registry seed for ASI soap dispenser shorthand.',
    active: true,
  },
  {
    id: 'takeoff-sd-bobrick-b822',
    sku: 'B-822',
    category: 'Toilet Accessories',
    family: 'soap dispenser',
    description: 'Soap Dispenser, Deck Mounted',
    manufacturer: 'Bobrick',
    model: 'B-822',
    uom: 'EA',
    baseMaterialCost: 62,
    baseLaborMinutes: 22,
    taxable: true,
    adaFlag: false,
    tags: ['sd', 'soap dispenser', 'bobrick', 'b-822', 'deck mounted'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (soap dispenser).',
    active: true,
  },
  {
    id: 'takeoff-sd-asi-0332',
    sku: 'ASI-0332',
    category: 'Toilet Accessories',
    family: 'soap dispenser',
    description: 'Soap Dispenser, Surface Mount',
    manufacturer: 'ASI',
    model: '0332',
    uom: 'EA',
    baseMaterialCost: 58,
    baseLaborMinutes: 20,
    taxable: true,
    adaFlag: false,
    tags: ['sd', 'soap dispenser', 'asi', '0332'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (soap dispenser).',
    active: true,
  },
  {
    id: 'takeoff-sd-bradley-6a00',
    sku: 'Bradley-6A00',
    category: 'Toilet Accessories',
    family: 'soap dispenser',
    description: 'Soap Dispenser, Surface Mount',
    manufacturer: 'Bradley',
    model: '6A00',
    uom: 'EA',
    baseMaterialCost: 68,
    baseLaborMinutes: 20,
    taxable: true,
    adaFlag: false,
    tags: ['sd', 'soap dispenser', 'bradley', '6a00'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (soap dispenser).',
    active: true,
  },
  {
    id: 'takeoff-hd-xlsb-rec',
    sku: 'HD-XL-SB-REC',
    category: 'Toilet Accessories',
    family: 'hand dryer',
    description: 'High Speed Hand Dryer XL-SB with Recess Kit',
    manufacturer: 'Excel Dryer',
    model: 'XL-SB',
    uom: 'EA',
    baseMaterialCost: 420,
    baseLaborMinutes: 35,
    taxable: true,
    adaFlag: false,
    tags: ['hd', 'hand dryer', 'xl-sb', 'recess kit'],
    notes: 'Takeoff registry seed for recess-mounted hand dryer shorthand.',
    active: true,
  },
  {
    id: 'takeoff-ptd-bobrick-b262',
    sku: 'B-262',
    category: 'Toilet Accessories',
    family: 'paper towel dispenser',
    description: 'Paper Towel Dispenser, Surface Mount (Multifold/C-Fold)',
    manufacturer: 'Bobrick',
    model: 'B-262',
    uom: 'EA',
    baseMaterialCost: 95,
    baseLaborMinutes: 22,
    taxable: true,
    adaFlag: false,
    tags: ['ptd', 'paper towel dispenser', 'bobrick', 'b-262'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (paper towel dispenser).',
    active: true,
  },
  {
    id: 'takeoff-ptd-bradley-250-15',
    sku: 'Bradley-250-15',
    category: 'Toilet Accessories',
    family: 'paper towel dispenser',
    description: 'Paper Towel Dispenser, Surface Mount (Multifold/C-Fold)',
    manufacturer: 'Bradley',
    model: '250-15',
    uom: 'EA',
    baseMaterialCost: 105,
    baseLaborMinutes: 22,
    taxable: true,
    adaFlag: false,
    tags: ['ptd', 'paper towel dispenser', 'bradley', '250-15'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (paper towel dispenser).',
    active: true,
  },
  {
    id: 'takeoff-ptd-asi-0210',
    sku: 'ASI-0210',
    category: 'Toilet Accessories',
    family: 'paper towel dispenser',
    description: 'Paper Towel Dispenser, Surface Mount (Multifold)',
    manufacturer: 'ASI',
    model: '0210',
    uom: 'EA',
    baseMaterialCost: 92,
    baseLaborMinutes: 22,
    taxable: true,
    adaFlag: false,
    tags: ['ptd', 'paper towel dispenser', 'asi', '0210'],
    notes: 'Manufacturer-backed seed for washroom accessory coverage (paper towel dispenser).',
    active: true,
  },
  {
    id: 'takeoff-scr-36',
    sku: 'SCR-36',
    category: 'Toilet Accessories',
    family: 'shower curtain rod',
    description: 'Shower Curtain Rod 36 inch Stainless Steel',
    manufacturer: 'ASI',
    model: 'SCR-36',
    uom: 'EA',
    baseMaterialCost: 55,
    baseLaborMinutes: 18,
    taxable: true,
    adaFlag: false,
    tags: ['scr', 'shower curtain rod', '36'],
    notes: 'Takeoff registry seed for shower curtain rod shorthand.',
    active: true,
  },
  {
    id: 'takeoff-sc',
    sku: 'SC',
    category: 'Toilet Accessories',
    family: 'shower curtain',
    description: 'Vinyl Shower Curtain - White',
    manufacturer: 'ASI',
    model: 'SC',
    uom: 'EA',
    baseMaterialCost: 28,
    baseLaborMinutes: 8,
    taxable: true,
    adaFlag: false,
    tags: ['sc', 'shower curtain'],
    notes: 'Takeoff registry seed for shower curtain shorthand.',
    active: true,
  },
  {
    id: 'takeoff-sch',
    sku: 'SCH',
    category: 'Toilet Accessories',
    family: 'shower curtain hooks',
    description: 'Shower Curtain Hooks (Set of 12)',
    manufacturer: 'ASI',
    model: 'SCH',
    uom: 'EA',
    baseMaterialCost: 12,
    baseLaborMinutes: 6,
    taxable: true,
    adaFlag: false,
    tags: ['sch', 'shower curtain hooks'],
    notes: 'Takeoff registry seed for shower curtain hook shorthand.',
    active: true,
  },
  {
    id: 'takeoff-fss',
    sku: 'FSS',
    category: 'Toilet Accessories',
    family: 'folding shower seat',
    description: 'Folding Shower Seat - Stainless Steel',
    manufacturer: 'ASI',
    model: 'FSS',
    uom: 'EA',
    baseMaterialCost: 310,
    baseLaborMinutes: 45,
    taxable: true,
    adaFlag: true,
    tags: ['fss', 'folding shower seat', 'shower seat'],
    notes: 'Takeoff registry seed for folding shower seat shorthand.',
    active: true,
  },
  {
    id: 'takeoff-b290-1836',
    sku: 'B290-1836',
    category: 'Toilet Accessories',
    family: 'mirror',
    description: 'Mirror B290 18x36 Stainless Steel Frame',
    manufacturer: 'Bobrick',
    model: 'B290',
    uom: 'EA',
    baseMaterialCost: 110,
    baseLaborMinutes: 20,
    taxable: true,
    adaFlag: false,
    tags: ['b290', 'mirror', '1836', '18x36'],
    notes: 'Takeoff registry seed for Bobrick mirror shorthand.',
    active: true,
  },
];

const FIND_EXISTING_SQL = `
    SELECT id
    FROM catalog_items
    WHERE id = ?
      OR lower(COALESCE(sku, '')) = lower(?)
      OR (lower(COALESCE(model, '')) = lower(?) AND lower(COALESCE(description, '')) = lower(?))
    LIMIT 1
  `;

async function findExistingItemIdPg(exec: DbExec, seedItem: CatalogItem): Promise<string | null> {
  const existing = await exec.get<{ id: string }>(FIND_EXISTING_SQL, [
    seedItem.id,
    seedItem.sku,
    seedItem.model || '',
    seedItem.description,
  ]);
  return existing?.id || null;
}

function findExistingItemIdSqlite(seedItem: CatalogItem): string | null {
  const existing = getEstimatorDb()
    .prepare(FIND_EXISTING_SQL)
    .get(seedItem.id, seedItem.sku, seedItem.model || '', seedItem.description) as { id: string } | undefined;
  return existing?.id || null;
}

/** Ensures takeoff shorthand catalog rows exist (idempotent). */
export async function ensureTakeoffCatalogSeeded(): Promise<void> {
  if (isPgDriver()) {
    await withPgTransaction(async (exec) => {
      for (const item of TAKEOFF_CATALOG_SEED_ITEMS) {
        const targetId = await findExistingItemIdPg(exec, item);
        const values = [
          item.sku,
          item.category,
          item.subcategory || null,
          item.family || null,
          item.description,
          item.manufacturer || null,
          item.brand || null,
          item.model || null,
          item.modelNumber || null,
          item.series || null,
          item.imageUrl || null,
          item.uom,
          item.baseMaterialCost,
          item.baseLaborMinutes,
          item.laborUnitType || null,
          item.taxable ? 1 : 0,
          item.adaFlag ? 1 : 0,
          JSON.stringify(item.tags || []),
          item.notes || null,
          item.active ? 1 : 0,
        ] as const;

        if (!targetId) {
          await exec.run(
            `
            INSERT INTO catalog_items (
              id, sku, category, subcategory, family, description, manufacturer, brand, model, model_number, series, image_url, uom,
              base_material_cost, base_labor_minutes, labor_unit_type, taxable, ada_flag, tags, notes, active
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
          `,
            [item.id, ...values]
          );
        } else {
          await exec.run(
            `
            UPDATE catalog_items
            SET sku = ?, category = ?, subcategory = ?, family = ?, description = ?, manufacturer = ?, brand = ?, model = ?, model_number = ?, series = ?, image_url = ?, uom = ?,
                base_material_cost = ?, base_labor_minutes = ?, labor_unit_type = ?, taxable = ?, ada_flag = ?, tags = ?, notes = ?, active = ?
            WHERE id = ?
          `,
            [...values, targetId]
          );
        }
      }
    });
    return;
  }

  withSqliteTransaction(() => {
    const db = getEstimatorDb();
    const upsert = db.prepare(`
    INSERT INTO catalog_items (
      id, sku, category, subcategory, family, description, manufacturer, brand, model, model_number, series, image_url, uom,
      base_material_cost, base_labor_minutes, labor_unit_type, taxable, ada_flag, tags, notes, active,
      install_labor_family
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

    const update = db.prepare(`
    UPDATE catalog_items
    SET sku = ?, category = ?, subcategory = ?, family = ?, description = ?, manufacturer = ?, brand = ?, model = ?, model_number = ?, series = ?, image_url = ?, uom = ?,
        base_material_cost = ?, base_labor_minutes = ?, labor_unit_type = ?, taxable = ?, ada_flag = ?, tags = ?, notes = ?, active = ?,
        install_labor_family = ?
    WHERE id = ?
  `);

    for (const item of TAKEOFF_CATALOG_SEED_ITEMS) {
      const targetId = findExistingItemIdSqlite(item);
      const values = [
        item.sku,
        item.category,
        item.subcategory || null,
        item.family || null,
        item.description,
        item.manufacturer || null,
        item.brand || null,
        item.model || null,
        item.modelNumber || null,
        item.series || null,
        item.imageUrl || null,
        item.uom,
        item.baseMaterialCost,
        item.baseLaborMinutes,
        item.laborUnitType || null,
        item.taxable ? 1 : 0,
        item.adaFlag ? 1 : 0,
        JSON.stringify(item.tags || []),
        item.notes || null,
        item.active ? 1 : 0,
        item.installLaborFamily || null,
      ] as const;

      if (!targetId) {
        upsert.run(item.id, ...values);
      } else {
        update.run(...values, targetId);
      }
    }
  });
}