import type { InstallIntelligenceWorkbook } from '../../shared/types/div10InstallIntelligence.ts';

/** Bundled workbook used when Sheets id is unset or load fails (tests + local dev). */
export function buildFallbackInstallIntelligenceWorkbook(): InstallIntelligenceWorkbook {
  return {
    loadedFrom: 'fallback',
    engineFlow: [],
    categoryProfiles: [
      {
        categoryKey: 'grab_bar',
        categoryLabel: 'Grab Bars',
        matchKeywords: 'grab bar|b-6806|gb-',
        defaultLaborFamily: 'grab_bar_install',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'baby_changing',
        categoryLabel: 'Baby Changing Stations',
        matchKeywords: 'baby changing|changing station|koala',
        defaultLaborFamily: 'toilet_accessory_install',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'partition',
        categoryLabel: 'Toilet Partitions',
        matchKeywords: 'partition|stall|compartment|pilaster',
        defaultLaborFamily: 'partition_install',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'locker',
        categoryLabel: 'Lockers',
        matchKeywords: 'locker|cubbie',
        defaultLaborFamily: 'locker_install',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'recessed_accessory',
        categoryLabel: 'Recessed Accessories',
        matchKeywords: 'recessed|semi-recessed',
        defaultLaborFamily: 'toilet_accessory_install',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'wall_protection',
        categoryLabel: 'Wall Protection',
        matchKeywords: 'wall protection|crash rail|corner guard|chair rail|acrovyn',
        defaultLaborFamily: 'wall_protection_lf',
        installable: true,
        active: true,
      },
      {
        categoryKey: 'mirror',
        categoryLabel: 'Mirrors',
        matchKeywords: 'mirror|b-290',
        defaultLaborFamily: 'mirror_install',
        installable: true,
        active: true,
      },
    ],
    laborFamilies: [
      {
        laborFamilyKey: 'grab_bar_install',
        laborFamilyName: 'Grab Bar Install',
        defaultUnit: 'EA',
        baseMinutesEach: 30,
        minMinutes: 20,
        active: true,
      },
      {
        laborFamilyKey: 'partition_install',
        laborFamilyName: 'Partition Install',
        defaultUnit: 'EA',
        baseMinutesEach: 90,
        minMinutes: 60,
        active: true,
      },
      {
        laborFamilyKey: 'locker_install',
        laborFamilyName: 'Locker Install',
        defaultUnit: 'EA',
        baseMinutesEach: 45,
        minMinutes: 30,
        active: true,
      },
      {
        laborFamilyKey: 'toilet_accessory_install',
        laborFamilyName: 'Toilet Accessory Install',
        defaultUnit: 'EA',
        baseMinutesEach: 20,
        minMinutes: 15,
        active: true,
      },
      {
        laborFamilyKey: 'mirror_install',
        laborFamilyName: 'Mirror Install',
        defaultUnit: 'EA',
        baseMinutesEach: 25,
        minMinutes: 20,
        active: true,
      },
      {
        laborFamilyKey: 'wall_protection_lf',
        laborFamilyName: 'Wall Protection LF',
        defaultUnit: 'LF',
        baseMinutesEach: 1.5,
        minMinutes: 1,
        active: true,
      },
    ],
    questionBank: [
      {
        questionKey: 'blocking_status',
        prompt: 'Is backing/blocking in place for this grab bar location?',
        fieldKey: 'blocking_status',
        inputType: 'dropdown',
        required: true,
        active: true,
      },
      {
        questionKey: 'baby_blocking_status',
        prompt: 'Is backing/blocking confirmed for the baby changing station?',
        fieldKey: 'blocking_status',
        inputType: 'dropdown',
        required: true,
        active: true,
      },
      {
        questionKey: 'compartment_count',
        prompt: 'How many compartments/stalls are included?',
        fieldKey: 'compartment_count',
        inputType: 'number',
        required: true,
        active: true,
      },
      {
        questionKey: 'mounting_style',
        prompt: 'Partition mounting style (floor/ceiling, ceiling-hung, etc.)?',
        fieldKey: 'mounting_style',
        inputType: 'text',
        required: true,
        active: true,
      },
      {
        questionKey: 'locker_openings',
        prompt: 'How many locker openings?',
        fieldKey: 'locker_openings',
        inputType: 'number',
        required: true,
        active: true,
      },
      {
        questionKey: 'locker_kd_status',
        prompt: 'Are lockers knocked-down (KD) or factory assembled?',
        fieldKey: 'locker_kd_status',
        inputType: 'dropdown',
        required: true,
        active: true,
      },
      {
        questionKey: 'rough_opening_responsibility',
        prompt: 'Who provides recessed rough openings?',
        fieldKey: 'rough_opening_responsibility',
        inputType: 'dropdown',
        required: true,
        active: true,
      },
      {
        questionKey: 'wall_protection_lf',
        prompt: 'Wall protection linear feet (LF)?',
        fieldKey: 'wall_protection_lf',
        inputType: 'number',
        required: true,
        active: true,
      },
      {
        questionKey: 'wall_protection_height',
        prompt: 'Wall protection height?',
        fieldKey: 'wall_protection_height',
        inputType: 'text',
        required: true,
        active: true,
      },
      {
        questionKey: 'wall_substrate',
        prompt: 'Wall substrate at install location?',
        fieldKey: 'wall_substrate',
        inputType: 'dropdown',
        required: false,
        active: true,
      },
    ],
    categoryQuestions: [
      { categoryKey: 'grab_bar', laborFamily: '', questionKey: 'blocking_status', active: true },
      { categoryKey: 'baby_changing', laborFamily: '', questionKey: 'baby_blocking_status', active: true },
      { categoryKey: 'partition', laborFamily: '', questionKey: 'compartment_count', active: true },
      { categoryKey: 'partition', laborFamily: '', questionKey: 'mounting_style', active: true },
      { categoryKey: 'locker', laborFamily: '', questionKey: 'locker_openings', active: true },
      { categoryKey: 'locker', laborFamily: '', questionKey: 'locker_kd_status', active: true },
      { categoryKey: 'recessed_accessory', laborFamily: '', questionKey: 'rough_opening_responsibility', active: true },
      { categoryKey: 'wall_protection', laborFamily: '', questionKey: 'wall_protection_lf', active: true },
      { categoryKey: 'wall_protection', laborFamily: '', questionKey: 'wall_protection_height', active: true },
      { categoryKey: 'wall_protection', laborFamily: '', questionKey: 'wall_substrate', active: true },
    ],
    defaultAssumptions: [
      { categoryKey: 'grab_bar', laborFamily: '', assumptionKey: 'blocking_status', defaultValue: '', active: true },
      { categoryKey: 'wall_protection', laborFamily: '', assumptionKey: 'wall_substrate', defaultValue: 'gypsum', active: true },
    ],
    installModifiers: [
      {
        modifierKey: 'tile_wall_labor',
        matchCategoryKeys: 'grab_bar,baby_changing,mirror,recessed_accessory',
        matchLaborFamilies: '',
        matchAssumptionKey: 'wall_substrate',
        matchAssumptionValue: 'tile',
        matchDescriptionRegex: '',
        laborMinutesAdd: 8,
        laborMultiplier: 1.1,
        reviewFlag: '',
        active: true,
      },
      {
        modifierKey: 'recessed_accessory_labor',
        matchCategoryKeys: 'recessed_accessory',
        matchLaborFamilies: '',
        matchAssumptionKey: '',
        matchAssumptionValue: '',
        matchDescriptionRegex: 'recessed|semi-recessed',
        laborMinutesAdd: 12,
        laborMultiplier: 1.05,
        reviewFlag: 'recessed_install_review',
        active: true,
      },
      {
        modifierKey: 'locker_knocked_down',
        matchCategoryKeys: 'locker',
        matchLaborFamilies: '',
        matchAssumptionKey: 'locker_kd_status',
        matchAssumptionValue: 'knocked_down|kd|unassembled',
        matchDescriptionRegex: '',
        laborMinutesAdd: 15,
        laborMultiplier: 1.15,
        reviewFlag: 'locker_kd_review',
        active: true,
      },
    ],
    reviewRules: [
      {
        ruleKey: 'grab_bar_blocking_unknown',
        matchCategoryKeys: 'grab_bar',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'blocking_status',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'blocking_unknown',
        active: true,
      },
      {
        ruleKey: 'baby_changing_blocking_unknown',
        matchCategoryKeys: 'baby_changing',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'blocking_status',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'blocking_unknown',
        active: true,
      },
      {
        ruleKey: 'partition_missing_compartments',
        matchCategoryKeys: 'partition',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'compartment_count',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'partition_layout_incomplete',
        active: true,
      },
      {
        ruleKey: 'partition_missing_mounting',
        matchCategoryKeys: 'partition',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'mounting_style',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'partition_mounting_unknown',
        active: true,
      },
      {
        ruleKey: 'locker_missing_openings',
        matchCategoryKeys: 'locker',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'locker_openings',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'locker_openings_unknown',
        active: true,
      },
      {
        ruleKey: 'locker_missing_kd',
        matchCategoryKeys: 'locker',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'locker_kd_status',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'locker_kd_unknown',
        active: true,
      },
      {
        ruleKey: 'recessed_rough_opening_unknown',
        matchCategoryKeys: 'recessed_accessory',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'rough_opening_responsibility',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'rough_opening_unknown',
        active: true,
      },
      {
        ruleKey: 'wall_protection_missing_lf',
        matchCategoryKeys: 'wall_protection',
        matchLaborFamilies: '',
        requiredAssumptionKey: 'wall_protection_lf',
        blockWhenMissingOrValues: 'unknown|',
        blockAutoPriceLabor: true,
        needsReview: true,
        reviewFlag: 'wall_protection_incomplete',
        active: true,
      },
    ],
    proposalClauses: [
      {
        clauseKey: 'tile_drilling',
        triggerCategoryKeys: 'grab_bar,mirror,baby_changing',
        triggerLaborFamilies: '',
        triggerAssumptionKey: 'wall_substrate',
        triggerAssumptionValue: 'tile',
        triggerReviewFlag: '',
        clientText: 'Drilling into tile substrates may require owner coordination and patch/paint by others.',
        internalOnly: false,
        active: true,
      },
      {
        clauseKey: 'blocking_review_internal',
        triggerCategoryKeys: 'grab_bar,baby_changing',
        triggerLaborFamilies: '',
        triggerAssumptionKey: '',
        triggerAssumptionValue: '',
        triggerReviewFlag: 'blocking_unknown',
        clientText: '',
        internalOnly: true,
        active: true,
      },
    ],
    vendorAliases: [
      { alias: 'fbm', canonicalVendor: 'FBM', active: true },
      { alias: 'ferguson', canonicalVendor: 'FBM', active: true },
      { alias: 'l&w', canonicalVendor: 'L&W Supply', active: true },
      { alias: 'lw supply', canonicalVendor: 'L&W Supply', active: true },
      { alias: 'gms', canonicalVendor: 'GMS', active: true },
      { alias: 'gypsum supply', canonicalVendor: 'GMS', active: true },
    ],
    vendorParserProfiles: [
      { vendorPattern: 'bobrick', profileKey: 'bobrick_standard', notes: '', active: true },
      { vendorPattern: 'fbm|ferguson', profileKey: 'distributor_tabular', notes: '', active: true },
    ],
  };
}
